### ISSUE TITLE
'CompVis/stable-diffusion-v1-4' is the correct path to a directory containing a config.json file

### ISSUE THREAD

**Issue by Daveshvats** [harubaru/discord-stable-diffusion#1]
[2022-09-07 12:24:02] ERROR: Extension 'src.bot.stablecog' raised an error: OSError: Can't load config for 'CompVis/stable-diffusion-v1-4'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have 
a local directory with the same name. Otherwise, make sure 'CompVis/stable-diffusion-v1-4' is the correct path to a directory containing a config.json file

**Comment by zeldatp151** [comment]
I have a work around, first you need to manually download the stable diffusion files from hugginface
```
git lfs install
git clone https://huggingface.co/CompVis/stable-diffusion-v1-4
```
Make a folder called CompVis in the root of the discord-stable-diffusion-main folder, and put the stable-diffusion-v1-4 folder inside it.

Then you need to install a few extra things that aren't listed in the requirements.txt. you need to install the nvidia cuda toolkit, you can google this, I am using 11.7.
you need to install the correct version of pytorch with cuda support
```
pip3 install scipy torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
```
now you should be able to run bat file and it should work, assuming you setup the bot in the discord dev sight correctly.
